import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, ArrowDownToLine, ArrowUpFromLine, Bolt, Boxes, ChevronDown, Cpu, Gauge, Keyboard as KeyboardIcon, Layers3, Lightbulb, MoreHorizontal, Play, Plus, RefreshCw, Save, Settings, Sparkles, Trash2, Upload, Zap } from "lucide-react";
import KeyboardView from "./components/KeyboardView";
import { Panel, Slider, Toggle } from "./components/Ui";
import { EFFECTS, EFFECT_NAME } from "./data/effects";
import { FN_SLOT, HID_OPTIONS, ROWS, SLOT_BY_HID, type KeyDef } from "./data/keyboard";
import * as api from "./lib/api";
import type { DeviceSummary, LightingSettings, MacroEvent, Page, PerformanceSettings, ProfileState, SnapPair } from "./lib/types";

const NAV: Array<{id:Page;label:string;icon:typeof Cpu}>=[
  {id:"device",label:"Device",icon:Cpu},{id:"lighting",label:"Lighting",icon:Lightbulb},{id:"keybinds",label:"Keybindings",icon:KeyboardIcon},{id:"snaptap",label:"Snap Tap",icon:Zap},{id:"macros",label:"Macros",icon:Play},{id:"performance",label:"Performance",icon:Gauge},{id:"profiles",label:"Profiles",icon:Layers3},{id:"settings",label:"Settings",icon:Settings}
];
const DEF_LIGHT:LightingSettings={effect:8,brightness:100,speed:75,direction:0,color:[148,5,57],multiColor:false};
const DEF_PERF:PerformanceSettings={pollingRate:1000,inputLatency:2,debounce:5,sleepTime:0};
const hex=([r,g,b]:[number,number,number])=>`#${[r,g,b].map(v=>v.toString(16).padStart(2,"0")).join("").toUpperCase()}`;
const parseHex=(s:string):[number,number,number]|null=>{const m=/^#?([0-9a-f]{6})$/i.exec(s.trim());return m?[parseInt(m[1].slice(0,2),16),parseInt(m[1].slice(2,4),16),parseInt(m[1].slice(4,6),16)]:null};
const keyName=(hid:number)=>ROWS.flat().find(k=>k.hid===hid)?.id ?? `HID_${hid}`;
const keyHid=(name:unknown,fallback:number)=>typeof name==="string"?(ROWS.flat().find(k=>k.id===name)?.hid??fallback):(typeof name==="number"?name:fallback);

export default function App(){
  const [page,setPage]=useState<Page>("device"),[device,setDevice]=useState<DeviceSummary|null>(null),[profile,setProfile]=useState(0),[state,setState]=useState<ProfileState|null>(null);
  const [lighting,setLighting]=useState<LightingSettings>(DEF_LIGHT),[performance,setPerformance]=useState<PerformanceSettings>(DEF_PERF),[snapEnabled,setSnapEnabled]=useState(false),[snapPairs,setSnapPairs]=useState<SnapPair[]>([{kind:0,key1:4,key2:7}]);
  const [selectedKey,setSelectedKey]=useState<KeyDef|null>(null),[layer,setLayer]=useState(1),[mappingKind,setMappingKind]=useState(1),[mappingCode,setMappingCode]=useState(4);
  const [macros,setMacros]=useState<Array<{id:number;name:string;events:MacroEvent[]}>>([{id:1,name:"Rapid Fire",events:[{hid:4,delay:25,pressed:true},{hid:4,delay:25,pressed:false}]}]),[activeMacro,setActiveMacro]=useState(1);
  const [busy,setBusy]=useState<string|null>(null),[status,setStatus]=useState("Ready"),[hexValue,setHexValue]=useState(hex(DEF_LIGHT.color));
  const fileRef=useRef<HTMLInputElement>(null);
  const run=async(label:string,fn:()=>Promise<void>)=>{setBusy(label);setStatus(label);try{await fn();setStatus(`${label} ✓`)}catch(e){console.error(e);setStatus(e instanceof Error?e.message:String(e))}finally{setBusy(null)}};
  const load=async(p=profile)=>run("Reading device",async()=>{const d=await api.scanDevice();const s=await api.readProfile(p);setDevice(d);setState(s);setLighting(s.lighting);setPerformance(s.performance);setSnapEnabled(s.snapTapEnabled);setSnapPairs(s.snapTapPairs.length?s.snapTapPairs:[{kind:0,key1:4,key2:7}]);setHexValue(hex(s.lighting.color))});
  useEffect(()=>{void load(0)},[]);
  const changeProfile=(p:number)=>run(`Profile ${p+1}`,async()=>{setProfile(p);setSelectedKey(null);await api.switchProfile(p);const s=await api.readProfile(p);setState(s);setLighting(s.lighting);setPerformance(s.performance);setSnapEnabled(s.snapTapEnabled);setSnapPairs(s.snapTapPairs);setHexValue(hex(s.lighting.color))});
  const snapSet=useMemo(()=>new Set(snapPairs.flatMap(x=>[x.key1,x.key2])),[snapPairs]);
  const slot=selectedKey?(selectedKey.special?FN_SLOT:SLOT_BY_HID.get(selectedKey.hid)):undefined;
  const binding=slot===undefined?undefined:state?.keyBindings.find(x=>x.slot===slot);
  useEffect(()=>{if(selectedKey){setMappingKind(binding?.kind??1);setMappingCode(binding?.code||selectedKey.hid||4)}},[selectedKey?.id,binding?.kind,binding?.code]);
  const colorCss=`rgb(${lighting.color.join(",")})`;

  const applyLight=()=>run("Applying lighting",()=>api.applyLighting(profile,lighting));
  const applyPerf=()=>run("Applying performance",()=>api.applyPerformance(profile,performance));
  const applySnap=()=>run("Applying Snap Tap",()=>api.applySnapTap(profile,snapEnabled,snapPairs));
  const applyBinding=()=>run("Applying key binding",async()=>{if(slot===undefined)throw new Error("This key has no firmware slot");const patch={slot,kind:mappingKind,code:mappingKind===0?0:mappingCode};await api.applyKeyBinding(profile,layer,patch);setState(s=>s?{...s,keyBindings:[...s.keyBindings.filter(x=>x.slot!==slot),patch]}:s)});
  const setPair=(i:number,p:Partial<SnapPair>)=>setSnapPairs(xs=>xs.map((x,n)=>n===i?{...x,...p}:x));
  const active=macros.find(m=>m.id===activeMacro)??macros[0];
  const patchMacro=(fn:(events:MacroEvent[])=>MacroEvent[])=>setMacros(xs=>xs.map(m=>m.id===activeMacro?{...m,events:fn(m.events)}:m));
  const saveMacro=()=>run(`Writing macro ${active.id}`,()=>api.writeMacro(active.id,active.events));

  const exportDp=()=>{const payload={filename:"Profile",SN:device?.serialNumber??"0x342D0xE40F012",value:{verify:"Darkproject",version:"1.0.1.0",data:{profile:{profileName:`Profile ${profile+1}`,profileid:profile+1,LightingIndex:lighting.effect,Lighting:[{value:lighting.effect,name:EFFECT_NAME[lighting.effect]??"Solid",BrightnessValue:lighting.brightness,RateValue:lighting.speed,AngleValue:lighting.direction,CustomColor:[lighting.color],MultiColor:lighting.multiColor}],Performance:{PollingRateValue:performance.pollingRate,InputLatencyValue:performance.inputLatency,DebounceTime:performance.debounce,SleepTime:performance.sleepTime},SnapTap:{flag:snapEnabled?1:0,snapTapIndex:0,snapTapShortcut:"ShiftRight",SnapTapData:snapPairs.map((x,i)=>({value:i,Key1:keyName(x.key1),Key2:keyName(x.key2),type:x.kind}))}},macro:macros}}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`DarkControl-Profile-${profile+1}.dp`;a.click();URL.revokeObjectURL(url);setStatus("Profile exported")};
  const importDp=async(file:File)=>{try{const raw=JSON.parse(await file.text()),p=raw?.value?.data?.profile??raw?.profile??raw;if(p.Performance)setPerformance({pollingRate:p.Performance.PollingRateValue??1000,inputLatency:p.Performance.InputLatencyValue??2,debounce:p.Performance.DebounceTime??5,sleepTime:p.Performance.SleepTime??0});const idx=p.LightingIndex??8,e=p.Lighting?.find?.((x:any)=>x.value===idx)??p.Lighting?.[0];if(e){const c=(e.CustomColor?.[0]??[148,5,57]) as [number,number,number];setLighting({effect:e.value??idx,brightness:e.BrightnessValue??100,speed:e.RateValue??75,direction:e.AngleValue??0,color:c,multiColor:!!e.MultiColor});setHexValue(hex(c))}if(p.SnapTap){setSnapEnabled(!!p.SnapTap.flag);setSnapPairs((p.SnapTap.SnapTapData??[]).map((x:any)=>({kind:x.type??0,key1:keyHid(x.Key1,4),key2:keyHid(x.Key2,7)})))}setStatus("Imported to editor — Apply to write") }catch{setStatus("Invalid .dp profile")}};

  return <div className={`app page-${page}`}>
    <aside className="sidebar"><div className="brand"><h1>DARK <span>CONTROL</span></h1><p>for Dark Project keyboards</p></div><nav>{NAV.map(n=><button key={n.id} className={page===n.id?"active":""} onClick={()=>setPage(n.id)}><n.icon size={21}/><span>{n.label}</span></button>)}</nav><div className="side-foot"><div className="pulse"><i/><i/><i/><i/><i/></div><b>DARK PROJECT</b><small>v0.1.0</small></div></aside>
    <main className="main">
      <header className="topbar"><div className="device-mini"><div className="mini-kbd">⌨</div><div><strong>{device?.productName?.replace("DPKB_","").replaceAll("_"," ")??"BUSHIDO 87 ANSI"}</strong><span className={`connection ${device?.connected?"on":""}`}><i/>{device?.connected?"Connected":"Preview mode"}</span></div><ChevronDown size={16}/></div><div className="meta"><span>VID: 0x{(device?.vendorId??0x342d).toString(16).toUpperCase()}</span><span>PID: 0x{(device?.productId??0xe40f).toString(16).toUpperCase()}</span><span>FW: {device?.firmware??"—"}</span></div><button className="icon-btn" onClick={()=>void load()}><RefreshCw size={18} className={busy?"spin":""}/></button><div className="grow"/><select className="profile-select" value={profile} onChange={e=>void changeProfile(+e.target.value)}>{[0,1,2].map(p=><option key={p} value={p}>Profile {p+1}</option>)}</select><button className="icon-btn" title="Export .dp" onClick={exportDp}><ArrowDownToLine size={18}/></button><button className="icon-btn" title="Import .dp" onClick={()=>fileRef.current?.click()}><ArrowUpFromLine size={18}/></button><button className="icon-btn"><MoreHorizontal size={18}/></button><input hidden ref={fileRef} type="file" accept=".dp,.json" onChange={e=>e.target.files?.[0]&&void importDp(e.target.files[0])}/></header>
      <div className="workspace">
        <div className="hero-grid"><Panel title="Bushido 87 ANSI" icon={KeyboardIcon} className="keyboard-card" action={<span className="hero-hint">Click a key to edit</span>}><KeyboardView color={lighting.color} selected={selectedKey?.id} onSelect={k=>{setSelectedKey(k);setPage("keybinds")}} snapHids={snapSet} keyBindings={state?.keyBindings}/></Panel><Panel title={device?.productName??"DPKB_BUSHIDO_87_ANSI"} icon={Cpu} className="device-card"><div className="device-art"><div/><span>87</span></div><dl><div><dt>Connection</dt><dd>USB</dd></div><div><dt>Firmware</dt><dd>{device?.firmware??"v27"} <b>● detected</b></dd></div><div><dt>Serial</dt><dd>{device?.serialNumber??"0x342D0xE40F012"}</dd></div><div><dt>Layout</dt><dd>{device?.layout??"ANSI"} (US)</dd></div><div><dt>Series</dt><dd>{device?.protocol??"CommonKeyboardSeries"}</dd></div></dl></Panel></div>

        <div className="mid-grid">
          <Panel title="Lighting" icon={Lightbulb} className="lighting-card" action={<button className="mini-action" onClick={applyLight}><Save size={14}/>Apply</button>}><div className="lighting-layout"><div className="color-picker"><input type="color" value={hex(lighting.color)} onChange={e=>{const c=parseHex(e.target.value)!;setLighting({...lighting,color:c});setHexValue(hex(c))}}/><div className="color-plane" style={{"--picker":colorCss} as any}><i/></div><div className="hue"/></div><div className="lighting-controls"><div className="hex-field"><i style={{background:colorCss}}/><input value={hexValue} onChange={e=>setHexValue(e.target.value)} onBlur={()=>{const c=parseHex(hexValue);if(c){setLighting({...lighting,color:c});setHexValue(hex(c))}else setHexValue(hex(lighting.color))}}/></div><Slider label="Brightness" value={lighting.brightness} onChange={v=>setLighting({...lighting,brightness:v})}/><Slider label="Speed" value={lighting.speed} onChange={v=>setLighting({...lighting,speed:v})}/><div className="directions"><b>Direction</b>{["→","↑","←","↓"].map((x,i)=><button key={x} className={lighting.direction===i?"active":""} onClick={()=>setLighting({...lighting,direction:i})}>{x}</button>)}</div></div></div></Panel>
          <Panel title="Quick Effects" icon={Sparkles} className="effects-card"><div className="effects-grid">{EFFECTS.map(e=><button key={e.id} className={(e.id===20?lighting.brightness===0:lighting.effect===e.id)?"active":""} onClick={()=>e.id===20?setLighting({...lighting,effect:8,brightness:0,color:[0,0,0],multiColor:false}):setLighting({...lighting,effect:e.id,brightness:Math.max(25,lighting.brightness)})}><span className={`fx fx-${e.id}`}>{e.glyph}</span><small>{e.name}</small></button>)}</div></Panel>
          <Panel title="Performance" icon={Gauge} className="performance-card" action={<button className="mini-action" onClick={applyPerf}><Save size={14}/>Apply</button>}><div className="seg"><b>Polling Rate</b>{[125,250,500,1000].map(v=><button key={v} className={performance.pollingRate===v?"active":""} onClick={()=>setPerformance({...performance,pollingRate:v})}>{v}</button>)}</div><div className="seg"><b>Input Latency</b>{[0,2,8,12].map(v=><button key={v} className={performance.inputLatency===v?"active":""} onClick={()=>setPerformance({...performance,inputLatency:v})}>{v}</button>)}</div><Slider label="Debounce Time" min={0} max={20} suffix=" ms" value={performance.debounce} onChange={v=>setPerformance({...performance,debounce:v})}/><Slider label="Sleep Timer" min={0} max={60} suffix=" min" value={performance.sleepTime} onChange={v=>setPerformance({...performance,sleepTime:v})}/></Panel>
        </div>

        <div className="bottom-grid">
          <Panel title="Keybindings" icon={KeyboardIcon} className="keybind-card" action={<div className="tabs"><button className={layer===1?"active":""} onClick={()=>setLayer(1)}>Base Layer</button><button className={layer===2?"active":""} onClick={()=>setLayer(2)}>FN Layer</button></div>}><div className="bind-editor"><div className="picked"><span>{selectedKey?.label||"A"}</span><div><b>{selectedKey?.id||"Select a key"}</b><small>firmware slot {slot??"—"}</small></div></div><select value={mappingKind} onChange={e=>setMappingKind(+e.target.value)}><option value={1}>Keyboard key</option><option value={0}>Disabled</option><option value={3}>Media / system (raw)</option><option value={5}>Macro</option><option value={8}>Profile switch</option><option value={9}>Mouse</option></select>{mappingKind===1&&<select value={mappingCode} onChange={e=>setMappingCode(+e.target.value)}>{HID_OPTIONS.map(x=><option key={`${x.hid}-${x.label}`} value={x.hid}>{x.label}</option>)}</select>}{mappingKind===5&&<select value={mappingCode} onChange={e=>setMappingCode(+e.target.value)}>{macros.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>}{mappingKind===8&&<select value={mappingCode} onChange={e=>setMappingCode(+e.target.value)}><option value={0}>Cycle up</option><option value={4}>Cycle down</option></select>}{mappingKind===9&&<select value={mappingCode} onChange={e=>setMappingCode(+e.target.value)}><option value={1}>Left click</option><option value={2}>Right click</option><option value={3}>Middle click</option><option value={4}>Back</option><option value={5}>Forward</option><option value={6}>Wheel up</option><option value={7}>Wheel down</option></select>}<button className="primary" disabled={slot===undefined} onClick={applyBinding}><Bolt size={15}/>Apply key</button></div></Panel>
          <Panel title="Snap Tap" icon={Zap} className="snap-card" action={<Toggle value={snapEnabled} onChange={setSnapEnabled}/>}><div className="snap-list">{snapPairs.slice(0,5).map((p,i)=><div className="snap-row" key={i}><select value={p.key1} onChange={e=>setPair(i,{key1:+e.target.value})}>{HID_OPTIONS.map(o=><option key={o.hid} value={o.hid}>{o.label}</option>)}</select><span>↔</span><select value={p.key2} onChange={e=>setPair(i,{key2:+e.target.value})}>{HID_OPTIONS.map(o=><option key={o.hid} value={o.hid}>{o.label}</option>)}</select><select value={p.kind} onChange={e=>setPair(i,{kind:+e.target.value})}><option value={0}>Last input</option><option value={1}>Key 1 priority</option><option value={2}>Key 2 priority</option><option value={3}>Neutral</option></select><button onClick={()=>setSnapPairs(xs=>xs.filter((_,n)=>n!==i))}><Trash2 size={14}/></button></div>)}</div><div className="card-actions"><button className="outline" disabled={snapPairs.length>=20} onClick={()=>setSnapPairs(xs=>[...xs,{kind:0,key1:26,key2:22}])}><Plus size={14}/>Add pair</button><button className="primary" onClick={applySnap}><Save size={14}/>Apply</button></div></Panel>
          <Panel title="Macros" icon={Play} className="macro-card"><div className="macro-tabs">{macros.map(m=><button key={m.id} className={activeMacro===m.id?"active":""} onClick={()=>setActiveMacro(m.id)}>{m.id}<span>{m.name}</span></button>)}</div>{active&&<div className="macro-events">{active.events.map((ev,i)=><div className="macro-event" key={i}><select value={ev.hid} onChange={e=>patchMacro(xs=>xs.map((x,n)=>n===i?{...x,hid:+e.target.value}:x))}>{HID_OPTIONS.map(o=><option key={o.hid} value={o.hid}>{o.label}</option>)}</select><input type="number" min={0} max={65535} value={ev.delay} onChange={e=>patchMacro(xs=>xs.map((x,n)=>n===i?{...x,delay:+e.target.value}:x))}/><button className={ev.pressed?"down":"up"} onClick={()=>patchMacro(xs=>xs.map((x,n)=>n===i?{...x,pressed:!x.pressed}:x))}>{ev.pressed?"DOWN":"UP"}</button><button onClick={()=>patchMacro(xs=>xs.filter((_,n)=>n!==i))}><Trash2 size={13}/></button></div>)}<div className="card-actions"><button className="outline" onClick={()=>patchMacro(xs=>[...xs,{hid:44,delay:40,pressed:true}])}><Plus size={14}/>Event</button><button className="primary" onClick={saveMacro}><Save size={14}/>Write</button></div></div>}<button className="text-add" onClick={()=>{const id=Math.max(0,...macros.map(m=>m.id))+1;if(id<=10){setMacros(xs=>[...xs,{id,name:`Macro ${id}`,events:[]}]);setActiveMacro(id)}}}><Plus size={14}/>New macro</button></Panel>
          <Panel title="Profiles" icon={Layers3} className="profiles-card"><div className="profile-list">{[0,1,2].map(p=><button key={p} className={profile===p?"active":""} onClick={()=>void changeProfile(p)}>Profile {p+1}<small>{profile===p?"Current":"Hardware"}</small></button>)}</div><div className="profile-buttons"><button onClick={()=>fileRef.current?.click()}><Upload size={14}/>Import .dp</button><button onClick={exportDp}><ArrowDownToLine size={14}/>Export .dp</button></div></Panel>
        </div>

        {page==="settings"&&<Panel title="Application & safety" icon={Settings} className="settings-panel"><div className="settings-grid"><div><Sparkles/><span>Interface</span><b>Dark graphite / Neon purple</b></div><div><Cpu/><span>Protocol</span><b>CommonKeyboardSeries · Report 7</b></div><div><Boxes/><span>Firmware</span><b>Flashing disabled by design</b></div><div><Activity/><span>Status</span><b>{status}</b></div></div></Panel>}
      </div>
      <footer className="statusbar"><span className={busy?"working":""}><i/>{busy||status}</span><span>{device?.connected?"Hardware writes enabled":"Browser preview · hardware calls mocked"}</span></footer>
    </main>
  </div>;
}
